config/routes.rb
Rails.application.routes.draw do
  root :to => 'business_types#index'

  get "/log-in" => "sessions#new"

  post "/log-in" => "sessions#create"

  get "/log-out" => "sessions#destroy", as: :log_out

  resources :business_types do
    resources :businesses, :except => [:index, :show]
  end

  resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/business.rb
class Business < ActiveRecord::Base
  belongs_to :business_type

  validates :name, :presence => true
end

app/models/business_type.rb
class BusinessType < ActiveRecord::Base
  has_many :businesses
  validates :name, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  validates_confirmation_of :password
  before_save :encrypt_password
  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end

  def self.authenticate(email, password)
    user = User.where(email: email).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/business_types_controller.rb
class BusinessTypesController < ApplicationController
  def index
    @business_types = BusinessType.all
  end

  def show
    @business_type = BusinessType.find(params[:id])
    @current_user = current_user
  end

  def new
    @business_type = BusinessType.new
  end

  def create
    @business_type = BusinessType.new(business_type_params)
    if @business_type.save
      flash[:notice] = "List successfully added!"
      redirect_to business_types_path
    else
      render :new
    end
  end

  def edit
    @business_type = BusinessType.find(params[:id])
  end

  def update
    @business_type = BusinessType.find(params[:id])
    if @business_type.update(business_type_params)
      redirect_to business_types_path
    else
      render :edit
    end
  end

  def destroy
    @business_type = BusinessType.find(params[:id])
    @businesses = @business_type.businesses
    @businesses.each do |b|
      b.destroy
    end
    @business_type.destroy
    redirect_to business_types_path
  end

private

  def business_type_params
    params.require(:business_type).permit(:name)
  end


end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  def new
    @business_type = BusinessType.find(params[:business_type_id])
    @business = @business_type.businesses.new
  end

  def create
    @business_type = BusinessType.find(params[:business_type_id])
    @business = @business_type.businesses.new(business_params)
    if @business.save
      redirect_to business_type_path(@business.business_type)
    else
      render :new
    end
  end

  def edit
    @business_type = BusinessType.find(params[:business_type_id])
    @business = Business.find(params[:id])
  end

  def update
    @bt = BusinessType.find(params[:business_type_id])
    @business = Business.find(params[:id])
    if @business.update(business_params)
      redirect_to business_type_path(@bt)
    else
      render :edit
    end
  end

  def destroy
    @business = Business.find(params[:id])
    @business.destroy
    redirect_to business_type_path(@business.business_type_id)
  end



private
  def business_params
    params.require(:business).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      flash[:notice] = "You've been logged in."
      session[:user_id] = @user.id
      redirect_to "/"
    else
      flash[:alert] = "There was a problem logging you in."
      redirect_to log_in_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice]="You've been logged out successfully"
    redirect_to "/log-in"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new(user_params)
    if @user.save
      flash[:notice]="welcome to the site"
      redirect_to "/"
    else
      flash[:alert]="THere was a problem creating your account. Please try again."
      redirect_to :back
    end
  end

  def create

  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/business_types/_form.html.erb
<%= render "layouts/errors", :object => @business_type %>

<%= form_for @business_type do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/business_types/_nav.html.erb
<% content_for(:navbar) do %>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">
          Wikipages
        </a>
        <a href="#">Home</a>
        <a href="/log-in">Log-in</a>
        <a href="/log-out">Log Out</a>
        <a><%= @current_user %></a>
      </div>
    </div>
  </nav>
<% end %>

app/views/business_types/edit.html.erb
<h1>EDIT BUSINESS TYPE</h1>

<%= render 'form' %>

app/views/business_types/index.html.erb
<h1>Business Types</h1>

<%= render 'nav' %>

<ul>
  <% @business_types.each do |type| %>
    <div class="well">
      <h6><%= link_to type.name, business_type_path(type) %></h6>
    </div>
  <% end %>
</ul>


<p>
  <%= link_to "NEW BUSINESS", new_business_type_path %>
</p>

<%= image_tag "rails.png" %>

app/views/business_types/new.html.erb
<h1>New Type</h1>

<%= render "form" %>

app/views/business_types/show.html.erb
<% content_for(:title, "K DUMMB") %>
<%= render 'nav' %>

<h1><%= @business_type.name %></h1>



<% if @business_type.businesses.any? %>
<h4>Here are all the listings for this business type:</h4>
<ul>
  <% @business_type.businesses.each do |business| %>
  <li>
    <%= business.name %> |
    <%= link_to "Edit Business", edit_business_type_business_path(@business_type, business) %> |
    <%= link_to "Delete", business_type_business_path(@business_type, business),
                                                      :data => { :confirm => "for real?",
                                                      :method => "delete"} %>
  </li>
  <% end %>
</ul>
<% else %>
  <p>
    There are no Businesses of this type yet.
  </p>
<% end %>


<p> <%= link_to "Edit", edit_business_type_path(@business_type) %> |

 <%= link_to "Delete", business_type_path(@business_type),
                          :data => {:confirm => "You sure bruh?",
                                    :method => "delete"}%> |

<%= link_to "New", new_business_type_business_path(@business_type) %>

<p><%= link_to "Return to Types", business_types_path %></p>

app/views/businesses/_form.html.erb
<%= render('layouts/errors', :object => @business) %>

<%= form_for [@business_type, @business] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <p><%= f.submit%></p>
<% end %>

app/views/businesses/edit.html.erb
<h1>Edit Business</h1>

<%= render 'form' %>

app/views/businesses/new.html.erb
<h1>New Business for <%= @business_type.name %></h1>

<%= render 'form' %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">

      <%= flash[:alert]%>
      <%= flash[:notice]%>


      <ul>
        <%= yield(:navbar) %>
      </ul>

      <%= yield %>
    </div>
  </body>
</html>

app/views/users/new.html.erb
<%=form_for User.new do |f| %>

<%=f.label :email %>

<%=f.text_field :email %>

<%=f.label :password %>

<%=f.password_field :password %>

<%=f.label :password_confirmation %>

<%=f.password_field :password_confirmation %>

<%=f.submit "Sign Up" %>

<%end%>